on:
  push:
  watch:
    types: [started]  

env:
  GROUP_ID: com.octokat.app
  ARTIFACT_ID: install-octokat-app
  VERSION: 1.0-SNAPSHOT
  CLASS_NAME: InstallApp
  TARGET_GROUP_ID: com.octokat.app
  TARGET_ARTIFACT_ID: octokat-app
  TARGET_VERSION: 1.0-SNAPSHOT
  TARGET_CLASS_NAME: PublishApp

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Add pom.xml with dependency
        run: |
          cat > pom.xml << EOM
          <?xml version="1.0" encoding="UTF-8"?>
          <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>${{ env.GROUP_ID }}</groupId>
            <artifactId>${{ env.ARTIFACT_ID }}</artifactId>
            <version>${{ env.VERSION }}</version>
            <dependencies>
              <dependency>
                <groupId>${{ env.TARGET_GROUP_ID }}</groupId>
                <artifactId>${{ env.TARGET_ARTIFACT_ID }}</artifactId>
                <version>${{ env.TARGET_VERSION }}</version>
              </dependency>
              <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>[4.13.1,)</version>
              </dependency>
            </dependencies>
          </project>
          EOM


      - name: Add settings.xml
        run: |
          cat > settings.xml << EOM
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2</url>
                    <releases><enabled>true</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                  </repository>
                  <repository>
                    <id>github</id>
                    <name>GitHub OWNER Apache Maven Packages</name>
                    <url>https://maven.pkg.github.com/${{ github.repository_owner }}/maven-publish</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <servers>
              <server>
                <id>github</id>
                <username>token</username>
                <password>${{ github.token }}</password>
              </server>
            </servers>
          </settings>
          EOM
          
      - name: Add ${{ env.CLASS_NAME }}.java file
        run: |
          SOURCE_PATH=src/main/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_PATH
          cat <<- END > $SOURCE_PATH/${{ env.CLASS_NAME }}.java
          package ${{ env.GROUP_ID }};

          import ${{ env.TARGET_GROUP_ID }}.${{ env.TARGET_CLASS_NAME }};

          public class ${{ env.CLASS_NAME }}
          {
              public static void main( String[] args )
              {
                  ${{ env.TARGET_CLASS_NAME }}.main( new String[0] );
              }
          }
          END

      - name: Add ${{ env.CLASS_NAME }}Test.java file
        run: |
          SOURCE_PATH=src/test/java/$(echo ${{ env.GROUP_ID }} | tr . /)
          mkdir -p $SOURCE_PATH
          cat <<- END > $SOURCE_PATH/${{ env.CLASS_NAME }}Test.java
          package ${{ env.GROUP_ID }};
          import static org.junit.Assert.assertTrue;
          import org.junit.Test;

          public class ${{ env.CLASS_NAME }}Test 
          {
              @Test
              public void shouldAnswerWithTrue()
              {
                  assertTrue( true );
              }
          }
          END

      - name: Install packages
        run: mvn install -s settings.xml --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Exec package
        run: mvn exec:java -D exec.mainClass=${{ env.GROUP_ID }}.${{ env.CLASS_NAME }} --no-transfer-progress

